#!/usr/bin/env bash

multiply() {
	local res=
	res=$(( $1 * $2 ))
	echo $res
}

res=0
pattern="mul\(([0-9]+),([0-9]+)\)"

while read -r text
do
	while IFS= read -r match; do
		if [[ $match =~ $pattern ]]; then
			sum=$(( ${BASH_REMATCH[1]} * ${BASH_REMATCH[2]} )) 
			(( res += sum ))
		fi
	done < <(echo $text | grep -E -o $pattern)
done < $1

echo $res
