#!/usr/bin/env bash

s=$(< /dev/stdin)

#split input string on ) and insert a new line to grab any do(), don'() and mul(x,y)
s=${s//)/)$'\n'}

pattern="mul\(([0-9]+),([0-9]+)\)"
do_pattern="do\(\)"
dont_pattern="don't\(\)"

res=0
enabled=true
# disable IFS to read in the array
while IFS= read -r line; do
	if [[ $line =~ $do_pattern ]]; then
		enabled=true
	elif [[ $line =~ $dont_pattern ]]; then
		enabled=false
	fi
	if [[ $line =~ $pattern ]] && $enabled ; then
		sum=$(( ${BASH_REMATCH[1]} * ${BASH_REMATCH[2]} ))
		((res+=sum))
	fi
done <<< "$s"

#corrected is 77055967
echo "result: "$res
