#!/usr/bin/env bash

issafe() {
	local array=($@)
	local len=${#array[@]}
	local tmp=$((array[1] - array[0]))

	for ((i=1; i < len; i++))
	do
		diff=$((array[i] - array[i-1]))
		# checking if all increasing or all decreasing
		if (( (diff < 0 && tmp > 0) || ( diff > 0 && tmp < 0)))
		then return 0
		fi
		# checking the level is within range
		if ! ((${diff#-} >= 1 && ${diff#-} <= 3))
		then return 0
		fi
	done
	return 1
}

count=0
while read -r line
do
	arr=($line)
	issafe ${arr[@]}
	((count+=$?))
done < $1
echo "count: "$count
